const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>"$"+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const store={get(k,d){try{return JSON.parse(localStorage.getItem("tomas_"+k))??d}catch{return d}},set(k,v){localStorage.setItem("tomas_"+k,JSON.stringify(v))}};
let balance=store.get("balance",10000), stats=store.get("stats",{wins:0,losses:0,rounds:0,bigWin:0,wagered:0,returned:0}), history=store.get("history",[]);
function save(){store.set("balance",balance);store.set("stats",stats);store.set("history",history);renderTop();renderStats();renderHistory();}
function renderTop(){$("#balance").textContent=money(balance)}
function toast(t){let x=$("#toast");x.textContent=t;x.className="show";clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.className="",2200)}
function validBet(v){v=Number(v);if(!Number.isFinite(v)||v<=0){toast("Enter a valid bet.");return false}if(v>balance){toast("Not enough virtual credits.");return false}return true}
function settle(game,bet,payout,msg){balance-=bet;balance+=payout;stats.rounds++;stats.wagered+=bet;stats.returned+=payout;let delta=payout-bet;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else if(delta<0)stats.losses++;history.unshift({game,delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();if(msg)toast(msg)}
function nav(route){$$(".page").forEach(p=>p.classList.toggle("active",p.id===route));$$(".side-link").forEach(b=>b.classList.toggle("active",b.dataset.route===route));$("#sidebar").classList.remove("open");location.hash=route}
$$("[data-route]").forEach(b=>b.addEventListener("click",e=>{let r=b.dataset.route;if(r)nav(r)}));
$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("open");
$("#resetBtn").onclick=()=>{if(confirm("Reset TOMA'S CASINO to $10,000 and clear statistics?")){balance=10000;stats={wins:0,losses:0,rounds:0,bigWin:0,wagered:0,returned:0};history=[];save();toast("Casino reset.")}};
$("#searchInput").addEventListener("input",e=>{let q=e.target.value.toLowerCase();$$(".game-card").forEach(c=>c.style.display=c.dataset.name.includes(q)?"":"none")});

const games=[
 {id:"blackjack",name:"Blackjack",cat:"Table Game",art:"♠",theme:"red",desc:"Beat the dealer",tag:"CLASSIC"},
 {id:"roulette",name:"Roulette",cat:"Table Game",art:"0",theme:"black",desc:"Spin the wheel",tag:"CLASSIC"},
 {id:"slots",name:"Crimson 7s",cat:"Slot",art:"7",theme:"red",desc:"Three-reel slot",tag:"ORIGINAL"},
 {id:"coin",name:"High / Low",cat:"Original",art:"◆",theme:"white",desc:"Call the flip",tag:"ORIGINAL"},
 {id:"dice",name:"Lucky Dice",cat:"Original",art:"⚄",theme:"black",desc:"Over or under",tag:"ORIGINAL"},
 {id:"double",name:"Double or Nothing",cat:"Original",art:"×2",theme:"red",desc:"Pick a side",tag:"ORIGINAL"}
];
function card(g){return `<article class="game-card" data-name="${g.name.toLowerCase()}" onclick="openGame('${g.id}')"><div class="game-art ${g.theme}"><span class="badge">${g.tag}</span><div class="art-symbol">${g.art}</div></div><div class="game-info"><strong>${g.name}</strong><small>${g.desc}</small></div></article>`}
function renderCards(){let featured=[games[0],games[1],games[2],games[3]], table=[games[0],games[1],games[4],games[5]], slots=[games[2]], originals=[games[3],games[4],games[5]];$("#featuredGrid").innerHTML=featured.map(card).join("");$("#tableGrid").innerHTML=table.map(card).join("");$("#slotsGrid").innerHTML=slots.map(card).join("");$("#tableFullGrid").innerHTML=table.map(card).join("");$("#originalsGrid").innerHTML=originals.map(card).join("")}
function renderStats(){$("#sWins").textContent=stats.wins;$("#sLosses").textContent=stats.losses;$("#sRounds").textContent=stats.rounds;$("#sBigWin").textContent=money(stats.bigWin);$("#sNet").textContent=money(stats.returned-stats.wagered)}
function renderHistory(){let html=history.length?history.map(h=>`<div class="history-row"><div><strong>${h.game}</strong><small>${h.time}</small></div><span>${h.delta>=0?"WIN":"LOSS"}</span><span class="${h.delta>=0?"positive":"negative"}">${h.delta>=0?"+":""}${money(h.delta)}</span><span></span></div>`).join(""):`<div class="empty">No rounds yet. Pick a game and take a seat.</div>`;$("#recentList").innerHTML=html;$("#recentHome").innerHTML=html}
function renderTopAnd(){renderTop();renderStats();renderHistory()}
const modal=$("#gameModal"),body=$("#gameBody");
function openGame(id){modal.classList.add("open");modal.setAttribute("aria-hidden","false");let g=games.find(x=>x.id===id);$("#modalTitle").textContent=g.name;$("#modalEyebrow").textContent=g.cat.toUpperCase();if(id==="blackjack")blackjack();if(id==="roulette")roulette();if(id==="slots")slots();if(id==="coin")coin();if(id==="dice")dice();if(id==="double")doubleGame()}
function closeGame(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");body.innerHTML=""}
$("#closeModal").onclick=closeGame;$("#modalBackdrop").onclick=closeGame;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeGame()});

function blackjack(){
 body.innerHTML=`<div class="game-stage"><div class="blackjack-table"><div class="hand"><div class="hand-title">DEALER <span id="dealerScore">?</span></div><div class="cards" id="dealerCards"></div></div><div class="hand"><div class="hand-title">PLAYER <span id="playerScore">0</span></div><div class="cards" id="playerCards"></div></div><div class="message" id="bjMsg">Place your bet and deal.</div></div><div class="bet-bar"><input class="bet-input" id="bjBet" type="number" value="100" min="1"><button class="chip" onclick="bjChip(25)">25</button><button class="chip" onclick="bjChip(100)">100</button><button class="chip" onclick="bjChip(500)">500</button><button class="mini-btn red" id="bjDeal">DEAL</button><button class="mini-btn" id="bjHit" disabled>HIT</button><button class="mini-btn" id="bjStand" disabled>STAND</button><button class="mini-btn" id="bjDouble" disabled>DOUBLE</button></div></div>`;
 let deck=[],p=[],d=[],bet=0,active=false,hidden=true;
 const ranks=["A","2","3","4","5","6","7","8","9","10","J","Q","K"],suits=["♠","♥","♦","♣"];
 function makeDeck(){let a=[];for(let s of suits)for(let r of ranks)a.push({s,r});return a.sort(()=>Math.random()-.5)}
 function val(c){return c.r==="A"?11:["J","Q","K"].includes(c.r)?10:+c.r}
 function total(h){let n=h.reduce((a,c)=>a+val(c),0),a=h.filter(c=>c.r==="A").length;while(n>21&&a--)n-=10;return n}
 function draw(){return deck.pop()}
 function card(c,back=false){if(back)return `<div class="card back center">T</div>`;let red=["♥","♦"].includes(c.s);return `<div class="card ${red?"red-suit":""}"><b>${c.r}</b><span>${c.s}</span><b>${c.r}</b></div>`}
 function render(){let dc=d.map((c,i)=>card(c,hidden&&i===0)).join(""),pc=p.map(c=>card(c)).join("");$("#dealerCards").innerHTML=dc;$("#playerCards").innerHTML=pc;$("#playerScore").textContent=total(p);$("#dealerScore").textContent=hidden?"?":total(d)}
 function end(){active=false;$("#bjHit").disabled=$("#bjStand").disabled=$("#bjDouble").disabled=true}
 window.bjChip=n=>$("#bjBet").value=n;
 $("#bjDeal").onclick=()=>{if(active)return;bet=Number($("#bjBet").value);if(!validBet(bet))return;deck=makeDeck();p=[draw(),draw()];d=[draw(),draw()];balance-=bet;hidden=true;active=true;render();$("#bjMsg").textContent="Your move.";$("#bjHit").disabled=$("#bjStand").disabled=$("#bjDouble").disabled=false;if(total(p)===21){$("#bjStand").click()}};
 $("#bjHit").onclick=()=>{if(!active)return;p.push(draw());render();if(total(p)>21){$("#bjMsg").textContent="Bust — dealer wins.";stats.rounds++;stats.losses++;history.unshift({game:"Blackjack",delta:-bet,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();end()}};
 $("#bjStand").onclick=()=>{if(!active)return;hidden=false;while(total(d)<17)d.push(draw());render();let pt=total(p),dt=total(d),pay=pt===21&&p.length===2&&dt!==21?bet*2.5:dt>21||pt>dt?bet*2:pt===dt?bet:0;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta);$("#bjMsg").textContent="You win "+money(delta)+" profit."}else if(delta<0){stats.losses++;$("#bjMsg").textContent="Dealer wins."}else $("#bjMsg").textContent="Push — bet returned.";history.unshift({game:"Blackjack",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();end()};
 $("#bjDouble").onclick=()=>{if(!active)return;if(balance<bet){toast("Not enough credits to double.");return}balance-=bet;bet*=2;p.push(draw());render();if(total(p)>21)$("#bjStand").click();else $("#bjStand").click()};
}
function roulette(){
 body.innerHTML=`<div class="game-stage roulette-layout"><div class="wheel" id="rw"><div class="wheel-number" id="rn">?</div></div><div class="message" id="rmsg">Choose a wager.</div><div class="roulette-picks" id="picks"><button class="pick selected" data-t="red">RED · 1:1</button><button class="pick" data-t="black">BLACK · 1:1</button><button class="pick" data-t="odd">ODD · 1:1</button><button class="pick" data-t="even">EVEN · 1:1</button><button class="pick" data-t="low">1–18 · 1:1</button><button class="pick" data-t="high">19–36 · 1:1</button><button class="pick" data-t="number">EXACT NUMBER · 35:1</button></div><div id="numWrap" style="display:none;margin-top:12px"><input class="bet-input" id="rnum" type="number" min="0" max="36" value="7"></div><div class="bet-bar"><input class="bet-input" id="rbet" type="number" value="100" min="1"><button class="mini-btn red" id="spin">SPIN</button></div></div>`;
 let type="red",rot=0;const reds=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36];
 $$("#picks .pick").forEach(b=>b.onclick=()=>{$$("#picks .pick").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");type=b.dataset.t;$("#numWrap").style.display=type==="number"?"block":"none"});
 $("#spin").onclick=()=>{let bet=Number($("#rbet").value);if(!validBet(bet))return;$("#spin").disabled=true;rot+=1440+Math.floor(Math.random()*360);$("#rw").style.transform=`rotate(${rot}deg)`;$("#rmsg").textContent="Spinning…";setTimeout(()=>{let n=Math.floor(Math.random()*37);$("#rn").textContent=n;let win=false,m=2;if(type==="red")win=reds.includes(n);if(type==="black")win=n!==0&&!reds.includes(n);if(type==="odd")win=n!==0&&n%2===1;if(type==="even")win=n!==0&&n%2===0;if(type==="low")win=n>=1&&n<=18;if(type==="high")win=n>=19&&n<=36;if(type==="number"){win=n===Number($("#rnum").value);m=36}let pay=win?bet*m:0;balance-=bet;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else stats.losses++;history.unshift({game:"Roulette",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();$("#rmsg").textContent=win?`Number ${n} — WIN ${money(delta)} profit!`:`Number ${n} — loss of ${money(bet)}.`;$("#spin").disabled=false},3600)}
}
function slots(){
 body.innerHTML=`<div class="game-stage slots-stage"><div class="reels"><div class="reel" id="s1">🍒</div><div class="reel" id="s2">7</div><div class="reel" id="s3">♦</div></div><div class="message" id="smsg">Match symbols to win.</div><div class="bet-bar"><input class="bet-input" id="sbet" type="number" value="50" min="1"><button class="chip" onclick="document.querySelector('#sbet').value=25">25</button><button class="chip" onclick="document.querySelector('#sbet').value=100">100</button><button class="mini-btn red" id="sspin">SPIN</button></div><table class="paytable"><tr><th>Combination</th><th>Return</th></tr><tr><td>♦ ♦ ♦</td><td>25×</td></tr><tr><td>7 7 7</td><td>15×</td></tr><tr><td>♣ ♣ ♣</td><td>10×</td></tr><tr><td>🍒 🍒 🍒</td><td>8×</td></tr><tr><td>Any pair</td><td>2×</td></tr></table></div>`;
 const syms=["🍒","♣","7","♦","★"];$("#sspin").onclick=()=>{let bet=Number($("#sbet").value);if(!validBet(bet))return;$("#sspin").disabled=true;let rs=[$("#s1"),$("#s2"),$("#s3")];rs.forEach(x=>x.classList.add("spin"));setTimeout(()=>{let a=syms[Math.floor(Math.random()*syms.length)],b=syms[Math.floor(Math.random()*syms.length)],c=syms[Math.floor(Math.random()*syms.length)];rs[0].textContent=a;rs[1].textContent=b;rs[2].textContent=c;rs.forEach(x=>x.classList.remove("spin"));let m=a===b&&b===c?({ "♦":25,"7":15,"♣":10,"🍒":8}[a]||4):a===b||b===c||a===c?2:0;let pay=bet*m;balance-=bet;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else stats.losses++;history.unshift({game:"Crimson 7s",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();$("#smsg").textContent=pay?`WIN — ${money(delta)} profit!`:"No match this spin.";$("#sspin").disabled=false},1200)}
}
function coin(){
 body.innerHTML=`<div class="game-stage coin-flip"><div class="coin" id="coin">T</div><div class="message" id="cmsg">Call heads or tails. Correct calls pay 2×.</div><div class="bet-bar"><input class="bet-input" id="cbet" type="number" value="100" min="1"><button class="mini-btn" id="heads">HEADS</button><button class="mini-btn red" id="tails">TAILS</button></div></div>`;
 ["heads","tails"].forEach(x=>$("#"+x).onclick=()=>{let bet=Number($("#cbet").value);if(!validBet(bet))return;$("#heads").disabled=$("#tails").disabled=true;$("#coin").classList.remove("flip");void $("#coin").offsetWidth;$("#coin").classList.add("flip");setTimeout(()=>{let result=Math.random()<.5?"heads":"tails",win=result===x,pay=win?bet*2:0;balance-=bet;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else stats.losses++;history.unshift({game:"High / Low",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();$("#coin").textContent=result==="heads"?"H":"T";$("#cmsg").textContent=win?`It was ${result}. You win ${money(delta)} profit!`:`It was ${result}. Better luck next time.`;$("#heads").disabled=$("#tails").disabled=false},850)})
}
function dice(){
 body.innerHTML=`<div class="game-stage coin-flip"><div class="coin" id="die">⚄</div><div class="message" id="dmsg">Roll 1–6. Pick over or under 3.5.</div><div class="bet-bar"><input class="bet-input" id="dbet" type="number" value="100" min="1"><button class="mini-btn" id="under">UNDER</button><button class="mini-btn red" id="over">OVER</button></div></div>`;
 ["under","over"].forEach(x=>$("#"+x).onclick=()=>{let bet=Number($("#dbet").value);if(!validBet(bet))return;$("#under").disabled=$("#over").disabled=true;$("#die").classList.add("flip");setTimeout(()=>{let n=1+Math.floor(Math.random()*6),win=x==="over"?n>3:n<4,pay=win?bet*2:0;balance-=bet;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else stats.losses++;history.unshift({game:"Lucky Dice",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();$("#die").textContent=["","⚀","⚁","⚂","⚃","⚄","⚅"][n];$("#dmsg").textContent=win?`Rolled ${n} — WIN ${money(delta)} profit!`:`Rolled ${n} — loss.`;$("#under").disabled=$("#over").disabled=false},800)})
}
function doubleGame(){
 body.innerHTML=`<div class="game-stage coin-flip"><div class="coin" id="dg">×2</div><div class="message" id="dgm">The button is the bet. 50% chance to double your wager.</div><div class="bet-bar"><input class="bet-input" id="dgb" type="number" value="100" min="1"><button class="mini-btn red" id="dgo">DOUBLE OR NOTHING</button></div></div>`;
 $("#dgo").onclick=()=>{let bet=Number($("#dgb").value);if(!validBet(bet))return;$("#dgo").disabled=true;setTimeout(()=>{let win=Math.random()<.5,pay=win?bet*2:0;balance-=bet;balance+=pay;let delta=pay-bet;stats.rounds++;stats.wagered+=bet;stats.returned+=pay;if(delta>0){stats.wins++;stats.bigWin=Math.max(stats.bigWin,delta)}else stats.losses++;history.unshift({game:"Double or Nothing",delta,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});history=history.slice(0,12);save();$("#dg").textContent=win?"2×":"0";$("#dgm").textContent=win?`Doubled! You made ${money(delta)} profit.`:"Nothing this time.";$("#dgo").disabled=false},650)}
}
function start(){renderCards();renderTopAnd();let r=location.hash.replace("#","")||"home";if($("#"+r))nav(r);else nav("home")}
window.addEventListener("hashchange",()=>{let r=location.hash.replace("#","");if($("#"+r))nav(r)});
start();
